#! /bin/sh

sxhkd &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
compton &
xmodmap ~/.Xmodmap &

bspc monitor VGA-1   -d I  II  III  IV V 
bspc monitor DVI-I-1 -d VI VII VIII IX X  

bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
